services:
  astra-backend:
    image: ${DOCKERHUB_USERNAME}/${IMAGE_REPO_NAME}:latest
    container_name: astra-backend-container
    ports:
      - "3000:3000" 
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}

