name: Deploy AstraBack 

on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/astraback
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-hetzner:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    timeout-minutes: 15
    
    steps:
      - name: Deploy to Hetzner Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HZ_IP }}
          username: ${{ secrets.HZ_USER }} 
          key: ${{ secrets.HZ_SSH_PRIVATE_KEY }} 
          port: ${{ secrets.HZ_SSH_PORT }}
          script: |
            set -e
            
            export API_KEY="${{ secrets.API_KEY }}"
            export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
            export IMAGE_REPO_NAME="astraback" 
            export APP_DIR="/home/${{ secrets.HZ_USER }}/AstraBack"

            cd $APP_DIR

            echo "Pulling latest changes from Repository..."
            git pull origin main

            echo "Pulling Docker image for AstraBack service..."
            docker compose pull astra-backend

            echo "Stopping and recreating AstraBack service..."
            docker compose up -d --force-recreate astra-backend

            echo "Cleaning up old Docker images..."
            docker image prune -af

            echo "Deployment to Hetzner via docker-compose completed!"
